### ISSUE TITLE
Share buttons on posts

### ISSUE THREAD

**Issue by anujmiddha** [moldedbits/moldedbits.github.io#20]
There is a section at the bottom of each post, "Share this post". There should be buttons to share on Facebook, Twitter and G+ here.

**Comment by anujmiddha** [comment]
@aksswami @aashishdhawan

**Comment by ashish-jajoria** [comment]
and one button for Linkedin share.

**Comment by anujmiddha** [comment]
So apparently we already have share buttons on the posts, they just get removed by ad block plus. Not sure what we want to do about it.
